### ISSUE TITLE
PyPi Examples are outdated

### ISSUE THREAD

**Issue by mtib** [tehmaze/ansi#15]
See: https://pypi.org/project/ansi/

In particular `reset` has moved from `ansi.colour` to `ansi.colour.fx`.

**Comment by mtib** [comment]
Either that or there's a more severe versioning issue, as my local version 0.2.0 differs from pypi's 0.2.0.

**Comment by jquast** [comment]
fixing this today thanks

**Comment by jquast** [comment]
closing with 0.3.0 release
