### ISSUE TITLE
Missing Type Information

### ISSUE THREAD

**Issue by b78** [tehmaze/ansi#17]
The library has a very nice API, but it is missing type information.

Is this to enable compatibility with python 2? Otherwise I would be happy to contribute some annotations.

**Comment by b78** [comment]
What is the minimum python version you would like to support? I would prefer 3.7.

**Comment by b78** [comment]
PR with 3.6 style annotations is open.

**Comment by b78** [comment]
@tehmaze - ping, could you have a look please? Would be awesome to release a new version soon.

**Comment by jquast** [comment]
your welcome to try https://github.com/jquast/blessed/ which solves for similar problem and does have type information, and by using `.pyi` files it is compatible with older releases of python

**Comment by b78** [comment]
Thank you @jquast. Does this mean this library is dead? It liked that it is a very lightweight way of achieving what I wanted to do, namely colour a few log messages. The PR adding typing information is ready and just needs to be merged.

**Comment by jquast** [comment]
I can’t merge or release this project, but I do try to help out @tehmaze when I can, sounds like he wants to merge but just might take some time, thanks for your effort so far though!

**Comment by b78** [comment]
Do you maybe want to have a quick look at the PR to tell me if it makes sense?

**Comment by untitaker** [comment]
@jquast you have both collaborator status and are a maintainer on pypi, same as me

**Comment by jquast** [comment]
@untitaker lol thanks you're right, i was on mobile and not using my eyes well, I have looked at the PR twice @b78 looks good I'll try to release 0.3.0 shortly

**Comment by b78** [comment]
Great, thank you @jquast!

**Comment by jquast** [comment]
released thanks
