### ISSUE TITLE
How to install v0.3.0?

### ISSUE THREAD

**Issue by kseistrup** [tehmaze/ansi#19]
What is the canonical way of installing v0.3.0? The command `pip install ansi` will just install an `ansi-0.3.0.dist-info` directory.

**Comment by mgorny** [comment]
It seems that `setup.cfg` was copied from another package and specifies the wrong package name.

**Comment by b78** [comment]
PR here with the fix from @mgorny: #20

**Comment by b78** [comment]
Actually, looking at it closer 0.3.0 has anyhow still somewhat broken types. I will push an update into the same branch.

**Comment by b78** [comment]
Btw, what is your opinion on 3.6 support - is it even needed. If we could use 3.7 things would be much cleaner:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/20678346/151696584-6219a7fe-1b35-42d6-aa1b-e30c44b14163.png">

**Comment by jquast** [comment]
I'm just pushing 0.3.1 to fix the broken install, you can worry about these silly types some other time. My own opinion is to retain legacy python versions for as long as it is possible to test for it and as long as it is downloaded and used, https://github.com/jquast/blessed/issues/226#issuecomment-968067717 but I'll follow whatever @tehmaze wishes for his project. https://github.com/tehmaze/ansi/issues/17#issuecomment-1006551315

**Comment by jquast** [comment]
sorry to miss your 2nd PR for typing, did not make 0.3.1 release, now it needs a version bump, anyway i'm going back to sleep!

**Comment by jquast** [comment]
0.3.4 is released and installing OK, thank you @kseistrup for reporting and thanks @b78 for helping.

**Comment by b78** [comment]
Thank you @jquast!
