### ISSUE TITLE
Without the py.typed marker type checking does not work

### ISSUE THREAD

**Issue by b78** [tehmaze/ansi#25]
#24

**Comment by jquast** [comment]
yes, sorry for delay, $DAYJOB ..

**Comment by jquast** [comment]
released, thanks again

**Comment by jquast** [comment]
If it matters, Your git config `user.email` is a mismatch to your github account email, so for example your github user is not listed in contributions for the repository, sorry !

**Comment by b78** [comment]
This is awesome, thank you @jquast for releasing it.
