### ISSUE TITLE
New release including a license

### ISSUE THREAD

**Issue by sdyroff** [tehmaze/ansi#8]
Hey,

it would be cool to release the current master because a license was added which would enable me to package ansi for fedora.

**Comment by untitaker** [comment]
:+1: @tehmaze

**Comment by untitaker** [comment]
@tehmaze If you don't have time for those things either, perhaps you could give me PyPI access as well?

**Comment by tehmaze** [comment]
@untitaker you have been added as package maintainer

**Comment by tehmaze** [comment]
Version 0.1.3 was released to PyPi.
