### ISSUE TITLE
Missing high-intensity colors

### ISSUE THREAD

**Issue by piranhaphish** [tehmaze/ansi#9]
I believe high-intensity colors (codes 90—97 and 100—107) were left out of the package under the assumption that they could be created with the addition of the bold (1) ANSI code.

While the Wikipedia page for ANSI code '1' does indicate "Bold or increased intensity", it doesn't actually have the same effect as selecting the intense flavor of colors. Code 1 does result in a brighter color, but it also results in bold text in the case of some characters (perhaps depending on the font). Using the high-intensity versions of the color results in the color being brighter but without the bold effect.

The attached picture demonstrates the difference for both foreground and background colors. There isn't a difference in the text color between lines 2 and 3, but you can see the horizontal box-drawing ('\u2500') is thicker. The difference is most apparent in the background versions where lines 5 and 6 share neither the foreground color, background color, nor the horizontal thickness.

![image](https://user-images.githubusercontent.com/22088189/53503453-b2fcb000-3a75-11e9-8227-156b03e1343e.png)

**Comment by tehmaze** [comment]
Ok, any idea what a generalized solution could be?

**Comment by piranhaphish** [comment]
The [Wikipedia page](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) calls these "bright" colors which I think was your intention with the "convenience wrappers", so I think it's just a matter of redefining those to the actual Graphic codes:

```
brightblack     = Graphic('90')
brightred       = Graphic('91')
brightgreen     = Graphic('92')
brightyellow    = Graphic('93')
brightblue      = Graphic('94')
brightmagenta   = Graphic('95')
brightcyan      = Graphic('96')
brightwhite     = Graphic('97')
```

**Comment by tehmaze** [comment]
Thanks for elaborating.
